Home/urls.py
from django.urls import path
from .views import landing_page, GetTest

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('test/', GetTest.as_view(), name='test')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile-update/', ProfileUpdateView.as_view(), name='edit-profile')

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='users_images/', blank=True, null=True, default='default_image.png')

    class Meta:
        db_table = 'CustomU'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from users.models import CustomUser

class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'image', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'image', 'email')

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import CustomUser
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin


from .forms import *
# Create your views here.


class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm()
        context = {
            'form': create_form
        }
        return render(request, 'register.html', context=context)

    def post(self, request):
        create_form = CustomUserForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'register.html', context=context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            'form': login_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect('landing_page')
        else:
            context = {
                'form': login_form
            }
            return render(request, 'login.html', context=context)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('landing_page')


class ProfileView(View):
    def get(self, request):
        return render(request, 'profile.html', {"user": request.user})


class ProfileUpdateView(View):
    def get(self, request):
        update_form = ProfileUpdateForm(instance=request.user)
        return render(request, 'profile_update.html', {"form": update_form})

    def post(self, request):
        update_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            update_form.save()
            return redirect('users:profile')
        else:
            return render(request, 'profile_update.html', {"form": update_form})

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>Login Page</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>


</form>
</body>
</html>

users/templates/profile.html
{% extends "base.html" %}

    <title>{% block title %} Profile {% endblock %}</title>

{% block content %}


<h1>Profile</h1>
<img alt="user-image" style="border-radius: 55px" src="{{ user.image.url }} " height="100px"><br>
Username:{{ user.username }}<br>
First name:{{ user.first_name }}<br>
Last name:{{ user.last_name }}<br>
Email:{{ user.email }}<br>

<a href="{% url 'users:edit-profile' %}">Edit Profile</a>
{% endblock content %}

users/templates/profile_update.html
{% extends "base.html" %}

    <title>{% block title %} Profile update {% endblock %}</title>

{% block content %}


<h1>Profile update</h1>
<form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Profile">

</form>

{% endblock content %}

users/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<h1>Register Page</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>


</form>

</body>
</html>