Home/urls.py
from django.urls import path
from .views import landing_page, GetTest

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('test/', GetTest.as_view(), name='test')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import *

app_name = 'Products'
urlpatterns = [
    path('books/', BookListView.as_view(), name='BookListView'),
    path('detail/<int:pk>', BookDetailView.as_view(), name='detail-view'),
    path('create/', BookCreateView.as_view(), name='create-book'),
    path('delete/<int:pk>', BookDeleteView.as_view(), name='delete-book'),
    path('add_review/<int:pk>', AddReviewView.as_view(), name='add-review'),
    path('edit_review/<int:pk>', ReviewUpdateView.as_view(), name='edit-review'),
    path('category/', CategoriesListView.as_view(), name='category'),
]

products/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class BookCategory(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        db_table = 'book_category'

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=64)


    class Meta:
        db_table = 'books_language'

    def __str__(self):
        return self.name


class Books(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)
    ISBN = models.CharField(max_length=100, blank=True, null=True)
    price = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to='users_images/', blank=True, null=True, default='default_book_img.png')
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    pages = models.IntegerField()
    category = models.ForeignKey(BookCategory, on_delete=models.CASCADE)

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


    class Meta:
        db_table = 'books'

    def __str__(self):
        return f'{self.title} - {self.category}'


class Author(models.Model):
    firstname = models.CharField(max_length=100, blank=True, null=True)
    lastname = models.CharField(max_length=100, blank=True, null=True)


    class Meta:
        db_table = 'author'

    def __str__(self):
        return f'{self.firstname} {self.lastname}'


class BookAuthor(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    class Meta:
        db_table = 'book_author'

    def __str__(self):
        return f'{self.book.title} - {self.author.firstname} {self.author.lastname}'


class Reviews(models.Model):
    comment = models.TextField()
    star_given = models.IntegerField(
        default=0,
        validators= [
            MaxValueValidator(5),
            MinValueValidator(0)
        ]
    )
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)

    class Meta:
        db_table = 'reviews'


    def __str__(self):
        return f'{self.comment} {self.book}'

products/forms.py
from django.forms import ModelForm

from products.models import Reviews


class AddReviewForm(ModelForm):
    class Meta:
        model = Reviews
        fields = ['comment', 'star_given']

class ReviewUpdateForm(ModelForm):
    class Meta:
        model = Reviews
        fields = '__all__'

products/views.py
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import AddReviewForm, ReviewUpdateForm
from .models import Books, Reviews, BookCategory, BookAuthor
from django.urls import reverse_lazy
# Create your views here.


class BookListView(View):
    def get(self, request):
        book = Books.objects.all().order_by('-id')
        return render(request, 'book/get_book.html', {'book': book})


class BookDetailView(View):
    def get(self, request, pk):
        book = Books.objects.get(pk=pk)
        reviews = Reviews.objects.filter(book=pk)
        print(reviews)
        context = {
            'book': book,
            'reviews': reviews
        }
        return render(request, 'book/book_detail.html', context=context)



class BookCreateView(CreateView):
    model = Books
    template_name = 'book/book_create.html'
    fields = '__all__'
    success_url = reverse_lazy('Products:BookListView')


class BookDeleteView(DeleteView):
    model = Books
    template_name = 'book/book_delete.html'
    success_url = reverse_lazy('Products:BookListView')


class AddReviewView(LoginRequiredMixin, View):
    def get(self, request, pk):
        books = Books.objects.get(pk=pk)
        add_review_form = AddReviewForm()
        context = {
            'books': books,
            'add_review_form': add_review_form
        }
        return render(request, 'book/add_review.html', context=context)

    def post(self, request, pk):
        books = Books.objects.get(pk=pk)
        add_review_form = AddReviewForm(request.POST)
        if add_review_form.is_valid():
            review = Reviews.objects.create(
                comment=add_review_form.cleaned_data['comment'],
                book=books,
                user=request.user,
                star_given=add_review_form.cleaned_data['star_given']
            )

            review.save()
            return redirect('Products:detail-view', pk=pk)



class ReviewUpdateView(View):
    def get(self, request, pk):
        review = Reviews.objects.get(pk=pk)
        update_review_form = ReviewUpdateForm(instance=review)
        context = {
            'update_review_form': update_review_form
        }
        return render(request, 'book/review_update.html', context=context)

    def post(self, request, pk):
        review = Reviews.objects.get(pk=pk)
        update_review_form = ReviewUpdateForm(request.POST, instance=review)
        if update_review_form.is_valid():
            update_review = update_review_form.save(commit=False)
            update_review.book_id = review.book_id
            update_review.save()
            return redirect('Products:BookListView', pk=review.book_id)
        else:
            return render(request, 'book/review_update.html', {'update_review_form': update_review_form})



class CategoriesListView(View):
    def get(self, request):
        category = BookCategory.objects.all()

        return render(request, 'book/products.html', {'categorys': category})

templates/book/add_review.html
<h1>{{ books.title }}</h1>
<form method="post" >
    {% csrf_token %}
    {{ add_review_form.as_p }}
    <input type="submit" value="Add Review">
</form>

templates/book/book_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Book</title>
</head>
<body>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

</body>
</html>

templates/book/book_delete.html
<form method="post" action="{% url 'Products:delete-book' object.pk %}">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit" class="confirm-delete-btn">Confirm</button>
</form>

<a href="{% url 'Products:BookListView' %}" class="back-btn">Back</a><br>

templates/book/book_detail.html
<head>
    <meta charset="UTF-8">
    <title>{{ book.title }}</title>
</head>
<body>
<h1>Title: {{ book.title }}</h1>
<img src="{{ book.image.url }}" height="200px"> <br><br>
<h4>Description: {{ book.description }}</h4>
<h4>ISBN: {{ book.ISBN }}</h4>
<h4>Language: {{ book.language }}</h4>
<h4>Price: {{ book.price }}</h4>
<h4>Pages: {{ book.pages }}</h4>
<h4>Category: {{ book.category }}</h4>

</body>
<a href="{% url 'Products:delete-book' book.pk %}" >Delete</a>
<h2>Reviews</h2>
<a href="{% url 'Products:add-review' book.pk %}" >Add Review</a>
{% for review in reviews %}
    <h4>{{ review.user.username }} | {{ review.star_given }}</h4>
    <p>{{ review.comment }}</p><hr>
{% endfor %}

templates/book/book_update.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Update</button>
</form>

templates/book/get_book.html
{% extends "base.html" %}

    <title>{% block title %} Books {% endblock %}</title>

{% block content %}
<body>
<h1>Books Page</h1>
<a href="{% url 'Products:create-book'%}">Add Book</a> <br><br><hr>

{% for i in book %}
    <a href="{% url 'Products:detail-view' i.pk %}">{{ i.title }}</a> <br><br>
{% endfor %}
</body>
{% endblock content %}

<a href="{% url 'Products:create-book' %}"><button>ADD BOOK</button></a><br><br>

templates/book/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Category</title>
</head>
<body>
{% for category in categorys %}

    {{ category.name }}<br>

{% endfor %}
</body>
</html>

templates/book/review_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Review</title>
</head>
<body>
<h1>Update Review</h1>
<form method="post" >
    {% csrf_token %}
    {{ update_review_form.as_p }}
    <input type="submit" value="Update Review">
</form>
</body>
</html>