Home/urls.py
from django.urls import path
from .views import landing_page, GetTest

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('test/', GetTest.as_view(), name='test')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import *

app_name = 'Products'
urlpatterns = [
    path('books/', BookListView.as_view(), name='BookListView'),
    path('detail/<int:pk>', BookDetailView.as_view(), name='detail-view'),
    path('create/', BookCreateView.as_view(), name='create-book'),
    path('delete/<int:pk>', BookDeleteView.as_view(), name='delete-book'),
    path('add_review/<int:pk>', AddReviewView.as_view(), name='add-review'),
    path('edit_review/<int:pk>', ReviewUpdateView.as_view(), name='edit-review'),
    path('category/', CategoriesListView.as_view(), name='category'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile-update/', ProfileUpdateView.as_view(), name='edit-profile')

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="success-message">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    <h4 class="alert-success text-center" style="padding-top: 5px; padding-bottom: 5px;">
                        {{ message }}
                    </h4>
                </li>
            {% endfor %}
         </ul>
     {% endif %}

</div>


        <a href="{% url 'Products:BookListView' %}">Books</a> /
        <a href="{% url 'users:register' %}">Register</a> /
        <a href="{% url 'test' %}">Test</a> /
        {% if request.user.is_authenticated %}
            <a href="{% url 'users:profile' %}">Profile</a> /
            <a href="{% url 'users:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'users:login' %}">Login</a>
        {% endif %}


       {% block content %}


        {% endblock content %}


<h6>Hell0</h6>
</body>
</html>

templates/get_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>THIS IS A TEST</title>
</head>
<body>
<h1>THIS IS A TEST</h1>
</body>
</html>

templates/landing_page.html
{% extends "base.html" %}

    <title>{% block title %} Home Page {% endblock %}</title>

{% block content %}
    <h1>Home page</h1>
{% endblock content %}